// <auto-generated />
using System;
using EShoppingZone.Product.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShoppingZone.Product.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260420065056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShoppingZone.Product.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RatingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Product_Category");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("IX_Product_MerchantId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Product_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Product_Type");

                    b.HasIndex("Category", "IsActive")
                        .HasDatabaseName("IX_Product_Category_Active");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 4, 20, 6, 50, 54, 856, DateTimeKind.Utc).AddTicks(8683),
                            Description = "Latest Apple iPhone with A17 Pro chip",
                            ImagesJson = "[]",
                            IsActive = true,
                            MRP = 150000m,
                            MerchantId = 1,
                            Name = "iPhone 15 Pro",
                            Price = 120000m,
                            RatingJson = "{}",
                            ReviewJson = "{}",
                            SpecificationsJson = "{}",
                            StockQuantity = 50,
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Penguin",
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 4, 20, 6, 50, 54, 856, DateTimeKind.Utc).AddTicks(8686),
                            Description = "Classic novel by F. Scott Fitzgerald",
                            ImagesJson = "[]",
                            IsActive = true,
                            MRP = 499m,
                            MerchantId = 2,
                            Name = "The Great Gatsby",
                            Price = 299m,
                            RatingJson = "{}",
                            ReviewJson = "{}",
                            SpecificationsJson = "{}",
                            StockQuantity = 100,
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Nike",
                            Category = "Apparel",
                            CreatedAt = new DateTime(2026, 4, 20, 6, 50, 54, 856, DateTimeKind.Utc).AddTicks(8688),
                            Description = "Comfortable running shoes",
                            ImagesJson = "[]",
                            IsActive = true,
                            MRP = 12999m,
                            MerchantId = 2,
                            Name = "Nike Air Max",
                            Price = 8999m,
                            RatingJson = "{}",
                            ReviewJson = "{}",
                            SpecificationsJson = "{}",
                            StockQuantity = 75,
                            Type = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Dove",
                            Category = "Personal Care",
                            CreatedAt = new DateTime(2026, 4, 20, 6, 50, 54, 856, DateTimeKind.Utc).AddTicks(8691),
                            Description = "Nourishing hair care",
                            ImagesJson = "[]",
                            IsActive = true,
                            MRP = 450m,
                            MerchantId = 3,
                            Name = "Dove Shampoo",
                            Price = 350m,
                            RatingJson = "{}",
                            ReviewJson = "{}",
                            SpecificationsJson = "{}",
                            StockQuantity = 200,
                            Type = "Hair Care"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
