{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=EShoppingZone_ProfileDB;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=True"
  },
  "Jwt": {
    "Secret": "dev-secret-key-for-development-only-32-chars",
    "Issuer": "EShoppingZone-Dev",
    "Audience": "EShoppingZoneUsers-Dev"
  }
}